name: Deploy Dev Stage
on:
  push:
    branches:
      - dev
      
jobs:
  unit-test:
    runs-on: ubuntu-latest
    steps:
    - name: Check out repository
      uses: actions/checkout@v1
    - name: Configure AWS Credentials
      uses: aws-actions/configure-aws-credentials@v1
      with:
        aws-access-key-id: ${{ secrets.SLS_AWS_ACCESS_KEY_ID }}
        aws-secret-access-key: ${{ secrets.SLS_AWS_SECRET_ACCESS_KEY }}
        aws-region: us-east-1
    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: 3.9
    - name: Install Dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt
#    - name: Run unit tests 
#      run: |
#        python -m pytest

  deploy-dev:
#    needs: unit-test
    runs-on: ubuntu-latest
    steps:
    
    - uses: actions/checkout@v1

    - name: Create public_key file
      run: |
        cat > /home/runner/work/photonranch-calendar/photonranch-calendar/public_key << EOF
        -----BEGIN CERTIFICATE-----
        ${{ secrets.AUTH0_PUBLIC_KEY }}
        -----END CERTIFICATE-----
        EOF
        
    - name: Create Auth0 secrets file
      run: |
        cat > /home/runner/work/photonranch-calendar/photonranch-calendar/secrets.json << EOF
        {
          "AUTH0_CLIENT_ID": "${{ secrets.AUTH0_CLIENT_ID }}"
        }
        EOF

    - name: Configure AWS Credentials
      uses: aws-actions/configure-aws-credentials@v1
      with:
        aws-access-key-id: ${{ secrets.SLS_AWS_ACCESS_KEY_ID }}
        aws-secret-access-key: ${{ secrets.SLS_AWS_SECRET_ACCESS_KEY }}
        aws-region: us-east-1
        
    - name: Set up Node
      uses: actions/setup-node@v1
      with:
        node-version: 16.14.0

    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: 3.9

    - name: Serverless Deploy
      uses: dhollerbach/github-action-serverless-with-python-requirements@master
      with:
        args: '--stage dev'
      env:
        SERVERLESS_ACCESS_KEY: ${{ secrets.SLS_SECRET_KEY }}
